### ISSUE TITLE
Padding in Bottom Menu for iPhone X +

### ISSUE THREAD

**Issue by EVSalomon** [EVNotify/EVNotifyPWA#1]
![pwa](https://user-images.githubusercontent.com/46657932/57569536-acd06b80-73f6-11e9-9ce5-0c29176d395a.png)

**Comment by GPlay97** [comment]
Thank you.

Should be a media query for iPhone (X?).

Will work on it later.

This is also opened for a Pull request 😄

**Comment by GPlay97** [comment]
#8
