### ISSUE TITLE
No access to login button on small mobile screens

### ISSUE THREAD

**Issue by BenderBU22** [EVNotify/EVNotifyPWA#12]
On small mobile devices or small screens you can't login because  the blue bottom bar hide the login button. Tested with iPhone SE and infotainment screen of Hyundai Ioniq. A landscape mode will be also very useful.

**Comment by GPlay97** [comment]
This should be fixed within commit 3cd7293feec3e200bf0651c24208c2bcc2eb4a27

Please confirm :)

**Comment by BenderBU22** [comment]
Thanks for fixing

**Comment by BenderBU22** [comment]
Thanks for fixing.
