### ISSUE TITLE
Imprint & data privacy page needed for compliance with german law

### ISSUE THREAD

**Issue by Pazekal90** [EVNotify/EVNotifyPWA#22]
Imprint & data privacy page needed for compliance with german law. Without those two pages the web app is remissable by lawyers. 

The best in first-aid would be to get those two pages via free generator like this one https://www.e-recht24.de/impressum-generator.html and https://www.e-recht24.de/muster-datenschutzerklaerung.html and link the generated content in the footer.

**Comment by Pazekal90** [comment]
After login the two pages must be linked, too.

**Comment by Pazekal90** [comment]
@GPlay97: If you want I can make a suggestion on that for position and content.

**Comment by GPlay97** [comment]
Its already available on the main domain.
Will be linked now also. Working on it.
After login, they can disappear. With login / registration (the usage of web interface), you automatically agree.
Currently you can only login, so you already agreed to privacy.

**Comment by Pazekal90** [comment]
Ok.
I don´t agree with disappearing after login. In the settings users can enter additional personal and sensitive informations like e-mail addresses. By sending this informations to servers you need to reference the data privacy page every time. 

I knew this because in my daily job this occurs weekly and we need to implement those informations on contact forms and other forms even the privacy conditions have been accepted at the start page.

**Comment by GPlay97** [comment]
Are you sure that this is required for web applications, that only work, if logged in and linked to the account, the user created in the app (or later directly from the interface) already accepted those things?
It's not like a normal webpage, where you can browse "anonymously" and sometimes fill out forms.
You only get access with your account. Otherwise you will have the form with those required links to accept and see all the compliance stuff.
But, to ensure, I can add a privacy section within settings from where you can see these things again.

**Comment by Pazekal90** [comment]
I´m really sure that on every page, where personal sensitive informations(name, e-mail address, ip-address(yes! Ip-addresses are personal informations, too), postal address s.o.) are sent to server, the data privacy page has to referenced.

**Comment by GPlay97** [comment]
Ok. Is it okay to make an additional section "Privacy" within settings page? From there you will have upcoming features (such as account deletion and so on) as well as the links to privacy / imprint?
Should be okay, because it is on the same page, isn't it?

**Comment by Pazekal90** [comment]
Yes, should a lot be better than the situation at the moment. 

I just searched other apps like NewMotion, EinfachStromLaden, E-Charge s.o. 
They have the imprint in their menu or a link in the footer to data privacy page on every page. or in the menu section at the very bottom in small font size.

![fU7YVB0vRPWgH1yYzCa32A_thumb_17aa](https://user-images.githubusercontent.com/25208775/58632518-fc170700-82e5-11e9-9d07-8c7bacecaadd.jpg)
