### ISSUE TITLE
Charge log detail - Charging speed chart - Add time and SOC as dimension...

### ISSUE THREAD

**Issue by Pazekal90** [EVNotify/EVNotifyPWA#35]
... to get the values most ev drivers want. "On which SOC in which time have I charged x kWh?"
Maybe you can speed to y axis und set x axis to time/SOC. 

![image](https://user-images.githubusercontent.com/25208775/61235328-8ea82400-a735-11e9-88e5-58c6d8e29a21.png)

**Comment by Pazekal90** [comment]
(Later this week I can make a pull request for this maybe)

**Comment by GPlay97** [comment]
This is a sparkline chart and should only give a quick overview. This is not intended for a full detailed chart. For this, the "Show chart" button will then render a new, full big chart with everything you need. I will work on the latter (also for the map) within the next few days. Should be live until end of this week.

**Comment by Pazekal90** [comment]
Ok thats also an option :) Just added those issues to keep in mind what I think needs to be done. If you want i can add some items to projects. Just tell me what's best for you. :)
