### ISSUE TITLE
Show chart & map buttons on log details page only if location data is available..

### ISSUE THREAD

**Issue by Pazekal90** [EVNotify/EVNotifyPWA#37]
... for PnP user this data is not available at the moment. So those buttons need to be hidden to get better usability here.

![image](https://user-images.githubusercontent.com/25208775/61236412-39214680-a738-11e9-821b-c9848babfa6e.png)

**Comment by GPlay97** [comment]
To be honest, they are currently // TODO buttons ;)

I will work on them within the next days :D

**Comment by Pazekal90** [comment]
I know I know :) If you want me to organize my recommendation differently just tell me :) I just want them to fit best in you process.

**Comment by GPlay97** [comment]
No, totally okay. Especially for such "missing visible features" ;) Good also for me to keep track of them. 

Maybe for "handling / usability" issues we need to find a better way to discuss, but for such things, issues are perfect.

Thanks.

**Comment by Pazekal90** [comment]
If you want we can text on twitter for some "fast" questions to not open too much issues :) :) https://twitter.com/Pazekal

**Comment by Pazekal90** [comment]
> If you want we can text on twitter for some "fast" questions to not open too much issues :) :) https://twitter.com/Pazekal

But you need to give me the ability to send you direct messages on twitter.
