### ISSUE TITLE
After a fresh log creation this chart is wrong way round...

### ISSUE THREAD

**Issue by Pazekal90** [EVNotify/EVNotifyPWA#40]
... It shows the end at the left side and the start on the right side. Just tested today after my last charging session. the 46 kWh was on the left. 

![image](https://user-images.githubusercontent.com/25208775/61407783-d5854d80-a8de-11e9-945b-6476ba5f3bfc.png)

**Comment by Pazekal90** [comment]
The screenshot shows the correct position. But i swear it was wrong way round 30 minutes after charging. :)

**Comment by EVSalomon** [comment]
the bug were fixed yesterday

**Comment by Pazekal90** [comment]
Ah thanks. Then it was my browser cache that plays games with me :)
