### ISSUE TITLE
Use "headroom" to get more information on mobile screen

### ISSUE THREAD

**Issue by Pazekal90** [EVNotify/EVNotifyPWA#6]
Use "headroom" to get more information on mobile screen without the need of scrolling. Headroom is just an example for the technology. It would also be possible to always hide the header and only show it up when user scrolls up on screen. 

Especially for people running the PWA on mobile while driving nearly everything needs to be visible to prevent user interactions => User keeps his/her attention on street.  

https://wicky.nillia.ms/headroom.js/

![image](https://user-images.githubusercontent.com/25208775/57581796-e4a1e680-74bc-11e9-87ce-07f53af416a1.png)

**Comment by GPlay97** [comment]
Thank you very much for this suggestion. This is a good idea. I will work on it, when things with higher priorities are done :)

**Comment by Pazekal90** [comment]
Added a new pull request to get this issue solved without the need of adding more external tools like headroom and get more APP-feeling in this PWA and more space for important informations.

https://github.com/EVNotify/EVNotifyPWA/pull/11
